services:
  redis:
    image: redis:6.2.5-alpine
    network_mode: host
  mongo:
    image: mongo:4.4.8-focal
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 2083:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
