# fly.toml file generated for teknologi-umum-bot on 2021-07-26T22:38:31+07:00

app = "teknologi-umum-bot"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "node"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

